Repository zonemaster/zonemaster, pull requests merged in 2020-11, with the labels that each got.

#899 Updated build environment documentation
  docs/internal-documentation/distrib-testing/BuildEnvironmentPreparation.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-test-distribution.md
Labels: A-Documentation

#900 Updated year, name and added link
  LICENSE
Labels: A-Documentation

#903 Main README: Updated for release v2020.1
  README.md
Labels: A-Documentation, P-High

#905 For release v2020.1 (zonemaster/zonemaster)
  Changes
  docs/specifications/tests/README.md
  docs/specifications/tests/TestMessages.md
Labels: P-High

#907 Fixes of test cases described
  Changes
Labels: P-High

#906 Fix merging develop into master
  docs/internal-documentation/maintenance/ReleaseProcess-release.md
Labels: A-Documentation, P-High

#909 Updated versions of components
  Changes
Labels: P-High

#910 Release v2020.1.1
  Changes
  README.md
Labels: P-High

#911 Merge develop into master (zonemaster/zonemaster)
  Changes
  README.md
Labels: P-High

#912 Updates for v2020.1.2 (Zonemaster/Zonemaster)
  Changes
Labels: P-High

#913 Merge develop into master (Zonemaster/Zonemaster)
  Changes
Labels: P-High

#904 Updated instructions for release process, build enviroment and zip file creation
  docs/internal-documentation/distrib-testing/BuildEnvironmentPreparation.md
  docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-test-distribution.md
  docs/internal-documentation/maintenance/ReleaseProcess-release.md
Labels: A-Documentation
