Repository zonemaster/zonemaster, pull requests merged in 2020-05, with the labels that each got.

#848 Update for release v2019.2
  Changes
Labels: A-Documentation

#850 Preparation for release of fix v2019.2.1
  Changes
Labels: A-Documentation

#852 Minor adjustment
  Changes
Labels: A-Documentation

#851 Merge Develop into Master for v2019.2.1 (Zonemaster/Zonemaster)
  Changes
Labels: A-Documentation

#853 Preparation for release v2019.2.2
  Changes
Labels: A-Documentation

#858 Merge Develop into Master for v2019.2.2 (Zonemaster/Zonemaster)
  Changes
Labels: A-Documentation

#856 Add a note to ignore warnings about missing .mo files.
  docs/internal-documentation/maintenance/ReleaseProcess.md
Labels: A-Documentation

#854 GNU extension have been removed from Makefiles
  docs/internal-documentation/maintenance/ReleaseProcess.md
Labels: A-Translation, S-ProposalExists

#810 Update DNSSEC02
  docs/specifications/tests/DNSSEC-TP/dnssec02.md
Labels: A-TestCase

#806 Updated Nameserver10
  docs/specifications/tests/Nameserver-TP/nameserver10.md
Labels: A-TestCase

#805 Updated DNSSEC13
  docs/specifications/tests/DNSSEC-TP/dnssec13.md
Labels: A-TestCase
