Repository zonemaster/zonemaster, pull requests merged in 2020-04, with the labels that each got.

#836 Update GUI release steps by adding nodejs install steps
  docs/internal-documentation/maintenance/ReleaseProcess.md
Labels: A-Documentation

#838 Updated to handle difference between FreeBSD Make and GNU Make
  docs/internal-documentation/maintenance/ReleaseProcess.md
Labels: A-Documentation

#839 Updated treatment of DS SHA-1 in DNSSEC01
  docs/specifications/tests/DNSSEC-TP/dnssec01.md
Labels: A-TestCase, S-ProposalExists

#837 Updated information on limitations with translation.
  README.md
Labels: A-Translation

#844 New logotype for Zonemaster
  README.md
  docs/images/zonemaster_logo_2020_color.png
  docs/images/zonemaster_logo_2020_color.svg
  docs/images/zonemaster_logo_black.png
  docs/images/zonemaster_logo_black.svg
  docs/images/zonemaster_logo_white.png
  docs/images/zonemaster_logo_white.svg
  docs/requirements/README.md
  docs/requirements/supporting-documents/README.md
  docs/specifications/README.md
  docs/specifications/test-types/README.md
Labels: A-Documentation, S-ProposalExists

#847 Updated translation status in README
  README.md
Labels: A-Translation
