Repository zonemaster/zonemaster, pull requests merged in 2021-12, with the labels that each got.

#1017 update node version
  docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md
Labels: A-Documentation

#1024 Generated files for release v2021.2 (zonemaster/zonemaster)
  docs/specifications/tests/ImplementedTestCases.md
  docs/specifications/tests/README.md
  docs/specifications/tests/TestMessages.md
Labels: A-Documentation, P-High

#1023 Preparation for release v2021.2 (zonemaster/zonemaster)
  Changes
Labels: A-Documentation, P-High

#1026 Merge develop into master (zonemaster/zonemaster)
  Changes
  LICENSE
  README.md
  USING.md
  docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md
  docs/internal-documentation/distrib-testing/Ubuntu-build-environment.md
  docs/internal-documentation/maintenance/Instructions-for-translators.md
  docs/internal-documentation/maintenance/IssueLabels.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-docker-image.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-test-distribution.md
  docs/internal-documentation/maintenance/ReleaseProcess-release.md
  docs/internal-documentation/maintenance/SupportCriteria.md
  docs/internal-documentation/templates/specifications/tests/MessageTagSpecification.md
  docs/internal-documentation/templates/specifications/tests/Template01.md
  docs/internal-documentation/templates/specifications/tests/TestCaseIdentifierSpecification.md
  docs/specifications/tests/Address-TP/address01.md
  docs/specifications/tests/DNSSEC-TP/dnssec02.md
  docs/specifications/tests/DNSSEC-TP/dnssec03.md
  docs/specifications/tests/DNSSEC-TP/dnssec08.md
  docs/specifications/tests/DNSSEC-TP/dnssec09.md
  docs/specifications/tests/DNSSEC-TP/dnssec10.md
  docs/specifications/tests/DNSSEC-TP/dnssec11.md
  docs/specifications/tests/DNSSEC-TP/dnssec13.md
  docs/specifications/tests/DNSSEC-TP/dnssec16.md
  docs/specifications/tests/DNSSEC-TP/dnssec17.md
  docs/specifications/tests/DNSSEC-TP/dnssec18.md
  docs/specifications/tests/ImplementedTestCases.md
  docs/specifications/tests/Nameserver-TP/nameserver01.md
  docs/specifications/tests/README.md
  docs/specifications/tests/TestMessages.md
Labels: P-High

#1021 Update instructions for updating GUI version
  docs/internal-documentation/maintenance/ReleaseProcess-release.md
Labels: A-Documentation, P-High

#1027 Corrections and clarifications
  docs/internal-documentation/maintenance/ReleaseProcess-create-docker-image.md
Labels: A-Documentation

#1025 Updated PostgreSQL version for FreeBSD
  README.md
Labels: A-Documentation

#1029 Preparation for v2021.2.1 release (zonemaster/zonemaster)
  Changes
Labels: P-High

#1030 Merge develop into master (Zonemaster/Zonemaster)
  Changes
  README.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-docker-image.md
  docs/internal-documentation/maintenance/ReleaseProcess-release.md
Labels: P-High
