Repository zonemaster/zonemaster, pull requests merged in 2021-05, with the labels that each got.

#938 Create DNSSEC15 (Existence of CDS and CDNSKEY)
  docs/specifications/tests/DNSSEC-TP/dnssec15.md
Labels: A-TestCase, FA-Basic04, FA-CDS-CDNSKEY

#944 Updates DNSSEC15 (Existence of CDS and CDNSKEY)
  docs/specifications/tests/DNSSEC-TP/dnssec15.md
Labels: FA-CDS-CDNSKEY

#939 Create DNSSEC16 (Validate CDS) and DNSSEC17 (Validate CDNSKEY)
  docs/specifications/tests/DNSSEC-TP/dnssec16.md
  docs/specifications/tests/DNSSEC-TP/dnssec17.md
Labels: A-TestCase, FA-Basic04, FA-CDS-CDNSKEY

#945 Codify test planning
  docs/internal-documentation/maintenance/ReleaseProcess-test-planning.md
  docs/internal-documentation/maintenance/ReleaseProcess.md
Labels: A-Documentation

#949 Adds missing packages needed for building Zonemaster-LDNS
  docs/internal-documentation/distrib-testing/FreeBSD-build-environment.md
Labels: P-High

#952 Updates DNSSEC specifications to lower level of no response
  docs/specifications/tests/DNSSEC-TP/dnssec02.md
  docs/specifications/tests/DNSSEC-TP/dnssec05.md
  docs/specifications/tests/DNSSEC-TP/dnssec10.md
  docs/specifications/tests/DNSSEC-TP/dnssec13.md
  docs/specifications/tests/DNSSEC-TP/dnssec14.md
Labels: A-TestCase, FA-Basic04, P-High

#954 Updates Syntax06 specification to lower level of no response
  docs/specifications/tests/Syntax-TP/syntax06.md
Labels: A-TestCase, FA-Basic04, P-High

#953 Updates NAMESERVER specifications to lower level of no response
  docs/specifications/tests/Nameserver-TP/nameserver01.md
  docs/specifications/tests/Nameserver-TP/nameserver02.md
  docs/specifications/tests/Nameserver-TP/nameserver05.md
  docs/specifications/tests/Nameserver-TP/nameserver10.md
  docs/specifications/tests/Nameserver-TP/nameserver11.md
  docs/specifications/tests/Nameserver-TP/nameserver12.md
  docs/specifications/tests/Nameserver-TP/nameserver13.md
  docs/specifications/tests/Nameserver-TP/nameserver14.md
Labels: A-TestCase, FA-Basic04, P-High

#951 Updates Delgation05 specification to lower level of no response
  docs/specifications/tests/Delegation-TP/delegation05.md
Labels: A-TestCase, FA-Basic04, P-High

#950 Updates CONSISTENCY specifications to lower level of no response
  docs/specifications/tests/Consistency-TP/consistency01.md
  docs/specifications/tests/Consistency-TP/consistency02.md
  docs/specifications/tests/Consistency-TP/consistency03.md
  docs/specifications/tests/Consistency-TP/consistency04.md
  docs/specifications/tests/Consistency-TP/consistency05.md
  docs/specifications/tests/Consistency-TP/consistency06.md
Labels: A-TestCase, FA-Basic04, P-High

#958 Fixes broken link in DNSSEC14
  docs/specifications/tests/DNSSEC-TP/dnssec14.md
Labels: A-TestCase

#955 Updates Zone10 specifications to lower level of no response
  docs/specifications/tests/Zone-TP/zone10.md
Labels: A-TestCase, FA-Basic04, P-High

#943 Preparation for v2021.1
  README.md
Labels: P-High

#959 Updates to refer to latest versions
  docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md
Labels: A-Documentation, P-High
