Repository zonemaster/zonemaster, pull requests merged in 2022-12, with the labels that each got.

#1109 Updates DNSSEC02: Better message for non-matching DS
  docs/specifications/tests/DNSSEC-TP/dnssec02.md
Labels: A-TestCase

#1117 Update Debian instructions for build environnement preparation
  docs/internal-documentation/distrib-testing/Debian-build-environment.md
Labels: A-Documentation

#1116 Update build env
  docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md
  docs/internal-documentation/distrib-testing/Ubuntu-build-environment.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-docker-image.md
Labels: A-Documentation, V-Patch

#1118 Update SystemTesting.md
  docs/internal-documentation/maintenance/SystemTesting.md
Labels: A-Documentation, V-Patch

#1114 Updates README for v2022.2
  README.md
Labels: A-Documentation, V-Patch

#1059 Updates of MethodsNT.md/MethodsV2.md and Methods.md
  docs/specifications/tests/Methods.md
  docs/specifications/tests/MethodsNT.md
  docs/specifications/tests/MethodsV2.md
Labels: A-TestCase, A-Documentation

#1019 Deb packages release process
  docs/internal-documentation/maintenance/ReleaseProcess-deb-packages.md
Labels: A-Documentation

#1120 Prepare release v2022.2 (zonemaster/zonemaster)
  Changes
  docs/specifications/tests/ImplementedTestCases.md
  docs/specifications/tests/README.md
  docs/specifications/tests/TestMessages.md
Labels: P-High

#1121 Merge develop into master (zonemaster/zonemaster)
  Changes
  README.md
  docs/internal-documentation/distrib-testing/Debian-build-environment.md
  docs/internal-documentation/distrib-testing/Ubuntu-Node.js-build-environment.md
  docs/internal-documentation/distrib-testing/Ubuntu-build-environment.md
  docs/internal-documentation/maintenance/Instructions-for-translators.md
  docs/internal-documentation/maintenance/IssueLabels.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-docker-image.md
  docs/internal-documentation/maintenance/ReleaseProcess-create-test-distribution.md
  docs/internal-documentation/maintenance/ReleaseProcess-deb-packages.md
  docs/internal-documentation/maintenance/ReleaseProcess-preparation.md
  docs/internal-documentation/maintenance/ReleaseProcess-release.md
  docs/internal-documentation/maintenance/StyleGuide.md
  docs/internal-documentation/maintenance/SystemTesting.md
  docs/internal-documentation/templates/specifications/tests/Template01.md
  docs/internal-documentation/templates/specifications/tests/TestCaseIdentifierSpecification.md
  docs/specifications/tests/Basic-TP/basic00.md
  docs/specifications/tests/Basic-TP/basic04.md
  docs/specifications/tests/Connectivity-TP/connectivity01.md
  docs/specifications/tests/Connectivity-TP/connectivity02.md
  docs/specifications/tests/Consistency-TP/consistency01.md
  docs/specifications/tests/Consistency-TP/consistency02.md
  docs/specifications/tests/Consistency-TP/consistency03.md
  docs/specifications/tests/Consistency-TP/consistency04.md
  docs/specifications/tests/Consistency-TP/consistency05.md
  docs/specifications/tests/Consistency-TP/consistency06.md
  docs/specifications/tests/DNSQueryAndResponseDefaults.md
  docs/specifications/tests/DNSSEC-TP/dnssec01.md
  docs/specifications/tests/DNSSEC-TP/dnssec02.md
  docs/specifications/tests/DNSSEC-TP/dnssec05.md
  docs/specifications/tests/DNSSEC-TP/dnssec08.md
  docs/specifications/tests/DNSSEC-TP/dnssec09.md
  docs/specifications/tests/DNSSEC-TP/dnssec10.md
  docs/specifications/tests/DNSSEC-TP/dnssec11.md
  docs/specifications/tests/DNSSEC-TP/dnssec13.md
  docs/specifications/tests/DNSSEC-TP/dnssec14.md
  docs/specifications/tests/DNSSEC-TP/dnssec15.md
  docs/specifications/tests/DNSSEC-TP/dnssec16.md
  docs/specifications/tests/DNSSEC-TP/dnssec17.md
  docs/specifications/tests/DNSSEC-TP/dnssec18.md
  docs/specifications/tests/Delegation-TP/delegation05.md
  docs/specifications/tests/ImplementedTestCases.md
  docs/specifications/tests/Methods.md
  docs/specifications/tests/MethodsNT.md
  docs/specifications/tests/MethodsV2.md
  docs/specifications/tests/Nameserver-TP/nameserver01.md
  docs/specifications/tests/Nameserver-TP/nameserver02.md
  docs/specifications/tests/Nameserver-TP/nameserver05.md
  docs/specifications/tests/Nameserver-TP/nameserver10.md
  docs/specifications/tests/Nameserver-TP/nameserver11.md
  docs/specifications/tests/Nameserver-TP/nameserver12.md
  docs/specifications/tests/Nameserver-TP/nameserver13.md
  docs/specifications/tests/Nameserver-TP/nameserver14.md
  docs/specifications/tests/README.md
  docs/specifications/tests/RequirementsAndNormalizationOfDomainNames.md
  docs/specifications/tests/Syntax-TP/syntax06.md
  docs/specifications/tests/TestMessages.md
  docs/specifications/tests/Zone-TP/zone01.md
  docs/specifications/tests/Zone-TP/zone09.md
  docs/specifications/tests/Zone-TP/zone10.md
Labels: P-High

#1123 Restores Basci00
  docs/specifications/tests/Basic-TP/basic00.md
Labels: A-Documentation, P-High
