Repository zonemaster/zonemaster, pull requests merged in 2023-06, with the labels that each got.

#1160 Removes CentOS linux from installation documents
  docs/public/installation/zonemaster-backend.md
  docs/public/installation/zonemaster-cli.md
  docs/public/installation/zonemaster-engine.md
  docs/public/installation/zonemaster-gui.md
Labels: A-Documentation, P-High, V-Patch

#1163 Clean up
  docs/public/configuration/backend.md
  docs/public/using/backend/rpcapi-reference.md
Labels: A-Documentation

#1166 Preparation for release v2023.1 (Zonemaster/Zonemaster)
  Changes
  docs/public/installation/zonemaster-gui.md
Labels: A-Documentation, P-High
