Repository zonemaster/zonemaster, pull requests merged in 2023-05, with the labels that each got.

#1152 Fix typos and inconsistencies in DNSSEC16 and DNSSEC17 specifications
  docs/public/specifications/tests/DNSSEC-TP/dnssec16.md
  docs/public/specifications/tests/DNSSEC-TP/dnssec17.md
Labels: T-Bug, A-TestCase

#1147 Improve centralized documentation
  .gitignore
  README.md
  docs/public/SUMMARY.md
  docs/public/configuration/README.md
  docs/public/configuration/backend.md
  docs/public/installation/README.md
  docs/public/installation/zonemaster-engine.md
  docs/public/installation/zonemaster-gui.md
  docs/public/specifications/tests/Address-TP/README.md
  docs/public/specifications/tests/Basic-TP/README.md
  docs/public/specifications/tests/Connectivity-TP/README.md
  docs/public/specifications/tests/Consistency-TP/README.md
  docs/public/specifications/tests/DNSSEC-TP/README.md
  docs/public/specifications/tests/Delegation-TP/README.md
  docs/public/specifications/tests/Nameserver-TP/README.md
  docs/public/specifications/tests/Syntax-TP/README.md
  docs/public/specifications/tests/Zone-TP/README.md
  docs/public/upgrading/README.md
  docs/public/upgrading/backend.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_1.0.3.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_1.1.0.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_11.0.0.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_5.0.0.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_5.0.2.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_8.0.0.md
  docs/public/upgrading/backend/upgrade_zonemaster_backend_ver_9.0.0.md
  docs/public/using/backend/rpcapi-reference.md
  utils/README.md
  utils/generateTestCaseList.pl
  utils/updateTestPlanReadme.pl
Labels: A-Documentation

#1151 Specification of test data and zone files for unit testing (2nd)
  .gitignore
  docs/public/specifications/test-zones/DNSSEC-TP/dnssec16.md
  docs/public/specifications/test-zones/Nameserver-TP/nameserver11.md
  docs/public/specifications/test-zones/README.md
  docs/public/specifications/test-zones/Zone-TP/zone09.md
  test-zone-data/COMMON/README.md
  test-zone-data/COMMON/arpa
  test-zone-data/COMMON/hintfile
  test-zone-data/COMMON/root-zone
  test-zone-data/COMMON/xa
  test-zone-data/DNSSEC-TP/dnssec16/README.md
  test-zone-data/DNSSEC-TP/dnssec16/cds-invalid-rrsig.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-matches-no-dnskey.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-matches-non-sep-dnskey.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-matches-non-zone-dnskey.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-not-signed-by-cds.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-signed-by-unknown-dnskey.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-unsigned.cfg
  test-zone-data/DNSSEC-TP/dnssec16/cds-without-dnskey.cfg
  test-zone-data/DNSSEC-TP/dnssec16/delete-cds.cfg
  test-zone-data/DNSSEC-TP/dnssec16/dnskey-not-signed-by-cds.cfg
  test-zone-data/DNSSEC-TP/dnssec16/dnssec16.cfg
  test-zone-data/DNSSEC-TP/dnssec16/dnssec16.xa
  test-zone-data/DNSSEC-TP/dnssec16/mixed-delete-cds.cfg
  test-zone-data/DNSSEC-TP/dnssec16/no-cds.cfg
  test-zone-data/DNSSEC-TP/dnssec16/not-aa.cfg
  test-zone-data/DNSSEC-TP/dnssec16/valid-cds.cfg
  test-zone-data/README.md
  test-zone-data/Zone-TP/zone09/COMMON.zone09.xa
  test-zone-data/Zone-TP/zone09/README.md
  test-zone-data/Zone-TP/zone09/hintfile-root-email-domain
  test-zone-data/Zone-TP/zone09/root-email-domain
  test-zone-data/Zone-TP/zone09/tld-email-domain-zone09
  test-zone-data/Zone-TP/zone09/zone09.cfg
  test-zone-data/Zone-TP/zone09/zone09.xa
  test-zone-data/add-ip.sh
  test-zone-data/address-plan.md
  test-zone-data/main.cfg
Labels: A-TestCase

#1156 Documentation: extract latest updates from other components
  docs/public/SUMMARY.md
  docs/public/configuration/backend.md
  docs/public/configuration/gui.md
  docs/public/installation/zonemaster-backend.md
  docs/public/installation/zonemaster-engine.md
  docs/public/using/backend/rpcapi-reference.md
Labels: A-Documentation
