Repository zonemaster/zonemaster, pull requests merged in 2023-07, with the labels that each got.

#1172 Updates release process due to moved document
  docs/internal/maintenance/ReleaseProcess-deb-packages.md
  docs/internal/maintenance/ReleaseProcess-release.md
Labels: A-Documentation, V-Patch

#1180 Preparation for release v2023.1.1 (Zonemaster/Zonemaster)
  Changes
Labels: P-High, V-Patch

#1181 Merge Releases/v2023.1.1 into Master (Zonemaster/Zonemaster)
  Changes
  README.md
  WISHLIST.md
  docs/contact-and-mailing-lists.md
  docs/public/README.md
  docs/public/SUMMARY.md
  docs/public/configuration/README.md
  docs/public/specifications/README.md
  docs/public/specifications/test-types/README.md
  docs/public/specifications/test-zones/DNSSEC-TP/README.md
  docs/public/specifications/test-zones/Nameserver-TP/README.md
  docs/public/specifications/test-zones/Zone-TP/README.md
  docs/public/specifications/tests/README.md
  docs/public/upgrading/README.md
  docs/public/using/README.md
  test-zone-data/README.md
Labels: P-High

#1178 Removes limitation on multiple batches
  docs/public/using/backend/rpcapi-reference.md
Labels: A-Documentation, V-Minor

#1184 fix dead links to lists
  docs/contact-and-mailing-lists.md
Labels: T-Bug, A-Documentation

#1185 Preparation for release v2023.1.2
  Changes
Labels: A-Documentation, P-High

#1186 Merge releases/v2023.1.2 into Master (Zonemaster/Zonemaster)
  Changes
  docs/contact-and-mailing-lists.md
Labels: P-High

#1187 Merge master into develop (zonemaster/zonemaster)
  Changes
  docs/contact-and-mailing-lists.md
Labels: P-High
