Repository zonemaster/zonemaster, pull requests merged in 2024-06, with the labels that each got.

#1271 Merge Releases/v2023.2.2 branch into develop branch
  README.md
  docs/public/SUMMARY.md
  docs/public/book.toml
  docs/public/configuration/README.md
  docs/public/configuration/backend.md
  docs/public/installation/README.md
  docs/public/installation/docker.md
  docs/public/installation/zonemaster-backend.md
  docs/public/installation/zonemaster-cli.md
  docs/public/installation/zonemaster-gui.md
  docs/public/installation/zonemaster-ldns.md
  docs/public/specifications/test-zones/README.md
  docs/public/specifications/tests/Address-TP/address02.md
  docs/public/specifications/tests/Connectivity-TP/connectivity01.md
  docs/public/specifications/tests/Connectivity-TP/connectivity02.md
  docs/public/specifications/tests/DNSSEC-TP/dnssec13.md
  docs/public/specifications/tests/DNSSEC-TP/dnssec18.md
  docs/public/specifications/tests/MasterTestPlan.md
  docs/public/specifications/tests/MethodsV2.md
  docs/public/specifications/tests/Nameserver-TP/nameserver15.md
  docs/public/specifications/tests/README.md
  docs/public/specifications/tests/RequirementsAndNormalizationOfDomainNames.md
  docs/public/using/backend/rpcapi-reference.md
Labels: P-High

#1273 Update ubuntu node.js build environment doc
  docs/internal/distrib-testing/Ubuntu-Node.js-build-environment.md
Labels: A-Documentation, V-Patch

#1276 Remove unused dependency
  docs/public/installation/zonemaster-cli.md
Labels: V-Patch
