Repository zonemaster/zonemaster, pull requests merged in 2024-11, with the labels that each got.

#1299 Creates test scenarios for Connectivity04
  docs/public/specifications/test-zones/Connectivity-TP/README.md
  docs/public/specifications/test-zones/Connectivity-TP/connectivity04.md
  test-zone-data/COMMON/xa
  test-zone-data/Connectivity-TP/connectivity04/README.md
  test-zone-data/Connectivity-TP/connectivity04/asnlookup.zonemaster.net.zone
  test-zone-data/Connectivity-TP/connectivity04/connectivity04.cfg
  test-zone-data/Connectivity-TP/connectivity04/connectivity04.xa.zone
  test-zone-data/Connectivity-TP/connectivity04/hintfile.zone
  test-zone-data/Connectivity-TP/connectivity04/root-zone.zone
  test-zone-data/Connectivity-TP/connectivity04/test-zones-output.md
  test-zone-data/address-plan.md
  test-zone-data/main.cfg
Labels: A-TestCase, V-Minor

#1298 Updates Connectivity04
  docs/public/specifications/tests/Connectivity-TP/connectivity04.md
Labels: A-TestCase

#1303 Updates Backend usage documents and makes global cache unexperimental
  docs/public/SUMMARY.md
  docs/public/configuration/global-cache.md
  docs/public/using/backend/README.md
  docs/public/using/backend/Using-Zonemaster-Backend-JSON-RPC-API.md
  docs/public/using/backend/Using-Zonemaster-Backend-for-batch-testing.md
  docs/public/using/backend/getting-started.md
  docs/public/using/backend/rpcapi-reference.md
Labels: A-Documentation

#1306 Include update of RELEASE.md in release process
  docs/internal/maintenance/ReleaseProcess-release.md
Labels: A-Documentation

#1307 Require ExtUtils::PkgConfig as dependency
  docs/internal/distrib-testing/Debian-build-environment.md
  docs/internal/distrib-testing/FreeBSD-build-environment.md
  docs/internal/distrib-testing/Ubuntu-build-environment.md
  docs/public/installation/zonemaster-engine.md
Labels: A-Documentation

#1310 Fixes broken link in Backend batch document
  docs/public/using/backend/Using-Zonemaster-Backend-for-batch-testing.md
Labels: T-Bug, A-Documentation

#1311 Fixes link in Connectivity04
  docs/public/specifications/tests/Connectivity-TP/connectivity04.md
Labels: T-Bug, A-Documentation

#1309 Update CLI documentation
  docs/public/SUMMARY.md
  docs/public/development/README.md
  docs/public/development/cli.md
  docs/public/installation/zonemaster-cli.md
  docs/public/using/cli.md
Labels: P-High, V-Patch

#1319 Adds named arguments
  docs/public/specifications/tests/ArgumentsForTestCaseMessages.md
Labels: A-Documentation

#1316 Updates UDP DNS size default value and adds text about it
  docs/public/specifications/tests/DNSQueryAndResponseDefaults.md
Labels: A-Documentation

#1320 Updates translation instructions
  docs/internal/maintenance/Instructions-for-translators.md
Labels: A-Documentation

#1321 Updates CLI installation instruction
  docs/public/installation/zonemaster-cli.md
Labels: T-Bug, A-Documentation

#1179 Rewrite of the specification of DNSSEC10
  docs/public/specifications/tests/DNSSEC-TP/dnssec10.md
Labels: A-TestCase
