Repository zonemaster/zonemaster, pull requests merged in 2024-03, with the labels that each got.

#1239 Updates backend installation instructions for FreeBSD
  docs/public/installation/zonemaster-backend.md
Labels: A-Documentation, P-High, V-Patch

#1240 Corrects and adjusts the global cache configuration document
  docs/public/configuration/global-cache.md
Labels: A-Documentation, P-High, V-Patch

#1233 Preparation for v2023.2 release
  docs/public/installation/prerequisites.md
Labels: A-Documentation, V-Patch

#1241 Preparation for release v2023.2 (Zonemaster/Zonemaster)
  Changes
  docs/public/installation/zonemaster-gui.md
Labels: P-High

#1246 Preparation for release v2023.2.1 (Zonemaster/Zonemaster)
  Changes
Labels: P-High
